environment        = "dev"
region             = "asia-southeast1"
project_name       = "gcp-devsecops-demo"
project_short_name = "gcpdemo"
project_id         = "gcp-devsecops-demo"
cluster_name       = "gcpdemo-gitops-dev"
